name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.13", "1.14", "1.15"]
    env:
      VERBOSE: 1
      GOFLAGS: -mod=readonly
      GOPROXY: https://proxy.golang.org

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Deps
        run: go mod download
        working-directory: ./v2

      - name: Build
        run: go build ./...
        working-directory: ./v2

      - name: Test
        run: go test -v ./...
        working-directory: ./v2
